AWSTemplateFormatVersion: 2010-09-09
Description: Stack for Creating Code Build components for LabelPrinting API
Metadata:
  CloudFormationScriptName: Create Code Build components for LabelPrinting API
  Purpose: "Create Code Build with IAM, Code Pipeline Components etc"
  Components: " Code Build, CodeDeploy, IAM"
  CreatedBy: Desmond.Soon@Amway.com
  CreatedDate: 2022-07-13
  Version: "1.0"
  PreRequisites: "IAM Role: Role and Policy needs created in advance."
Parameters:
  Region:
    Description: Specify the region where service will be deployed.
    Type: String
    Default: Apac
  ServiceName:
    Description: Specify the name of the service to be deployed.
    Type: String
    Default: LabelPrintingAPI
  Environment:
    Description: Specify the environment value
    Type: String
    Default: Dev
  Country:
    Description: Specify the Country value
    Type: String
    Default: Msb
  Stage:
    Description: Specify the Stage value
    Type: String
    Default: dev
  GitHubRepo:
    Description: Specify the GitHub Repository value
    Type: String
    Default: https://github.com/AmwayAPAC/cmp-zendesk-migration.git
  GitHubBranch:
    Description: Specify the GitHub branch value
    Type: String
    Default: dev

Resources:
  CiCdIamRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: "sts:AssumeRole"
      RoleName: !Join
        - ""
        - - !Ref Region
          - !Ref Country
          - !Ref Environment
          - !Ref ServiceName
          - "CodeBuildRole"
      Path: /
      Tags:
        - Key: Name
          Value: !Join
            - ""
            - - !Ref Region
              - !Ref Country
              - !Ref Environment
              - !Ref ServiceName
              - "CodeBuildRole"
      Policies:
        - PolicyName: S3BucketPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListAllMyBuckets
                Resource:
                  - arn:aws:s3:::*
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:GetObjectAcl
                  - s3:DeleteObject
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:PutPublicAccessBlock
                  - "*"
                Resource:
                  - "*"
        - PolicyName: AssumeRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "sts:*"
                Resource:
                  - !Join
                    - ""
                    - - "arn:aws:iam::"
                      - !Ref "AWS::AccountId"
                      - ":role/"
                      - !Ref Region
                      - !Ref Country
                      - !Ref Environment
                      - !Ref ServiceName
                      - "CodeBuildRole"
        - PolicyName: CloudwatchPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:CreateLogGroup"
                  - "logs:PutRetentionPolicy"
                  - "logs:DeleteLogGroup"
                  - "cloudwatch:PutMetricAlarm"
                  - "cloudwatch:DescribeAlarmHistory"
                  - "cloudwatch:EnableAlarmActions"
                  - "cloudwatch:DeleteAlarms"
                  - "cloudwatch:DisableAlarmActions"
                  - "cloudwatch:DescribeAlarmsForMetric"
                  - "cloudwatch:DescribeAlarms"
                  - "cloudwatch:SetAlarmState"
                  - "cloudwatch:PutCompositeAlarm"
                Resource:
                  - !Join [
                      "",
                      [
                        "arn:aws:logs:",
                        !Ref "AWS::Region",
                        ":",
                        !Ref "AWS::AccountId",
                        ":log-group:/aws/codebuild/",
                        !Sub "Apac${Country}${Environment}${ServiceName}*",
                      ],
                    ]
                  - !Join [
                      "",
                      [
                        "arn:aws:codebuild:",
                        !Ref "AWS::Region",
                        ":",
                        !Ref "AWS::AccountId",
                        ":build/",
                        !Ref Region,
                        !Ref Country,
                        !Ref Environment,
                        !Ref ServiceName,
                        "CodeBuild:",
                        "*",
                      ],
                    ]
                  - !Join [
                      "",
                      [
                        "arn:aws:logs:",
                        !Ref "AWS::Region",
                        ":",
                        !Ref "AWS::AccountId",
                        ":log-group:/aws/codebuild/",
                        !Ref Region,
                        !Ref Country,
                        !Ref Environment,
                        !Ref ServiceName,
                        "*",
                      ],
                    ]
                  - !Join
                    - ""
                    - - "arn:aws:logs:"
                      - !Ref "AWS::Region"
                      - ":"
                      - !Ref "AWS::AccountId"
                      - ":log-group:/aws/lambda/Apac"
                      - !Ref Country
                      - !Ref Environment
                      - !Ref ServiceName
                      - "*"
                  - !Join
                    - ""
                    - - "arn:aws:logs:"
                      - !Ref "AWS::Region"
                      - ":"
                      - !Ref "AWS::AccountId"
                      - ":log-group:"
                      - !Ref Country
                      - !Ref Environment
                      - !Ref ServiceName
                      - "*"
                  - "*"
              - Effect: Allow
                Action:
                  - "codebuild:CreateReportGroup"
                  - "codebuild:CreateReport"
                  - "codebuild:UpdateReport"
                  - "codebuild:BatchPutTestCases"
                Resource:
                  - !Join [
                      "",
                      [
                        "arn:aws:logs:",
                        !Ref "AWS::Region",
                        ":",
                        !Ref "AWS::AccountId",
                        ":log-group:/aws/codebuild/",
                        !Ref Region,
                        !Ref Country,
                        !Ref Environment,
                        !Ref ServiceName,
                      ],
                    ]
                  - !Join [
                      "",
                      [
                        "arn:aws:logs:",
                        !Ref "AWS::Region",
                        ":",
                        !Ref "AWS::AccountId",
                        ":log-group:/aws/codebuild/",
                        !Ref Region,
                        !Ref Country,
                        !Ref Environment,
                        !Ref ServiceName,
                        ":*",
                      ],
                    ]
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:UpdateEventSourceMapping"
                  - "lambda:ListFunctions"
                  - "lambda:ListVersionsByFunction"
                  - "lambda:GetLayerVersion"
                  - "lambda:GetEventSourceMapping"
                  - "lambda:GetFunction"
                  - "lambda:ListAliases"
                  - "lambda:PublishLayerVersion"
                  - "lambda:UpdateFunctionConfiguration"
                  - "lambda:GetFunctionConfiguration"
                  - "lambda:GetLayerVersionPolicy"
                  - "lambda:UpdateAlias"
                  - "lambda:UpdateFunctionCode"
                  - "lambda:ListLayers"
                  - "lambda:PublishVersion"
                  - "lambda:GetAlias"
                  - "lambda:*"
                Resource:
                  - !Join
                    - ""
                    - - "arn:aws:lambda:"
                      - !Ref "AWS::Region"
                      - ":"
                      - !Ref "AWS::AccountId"
                      - ":function:"
                      - !Ref Region
                      - !Ref Country
                      - !Ref Environment
                      - !Ref ServiceName
                      - "*"
                  - !Join
                    - ""
                    - - "arn:aws:lambda:"
                      - !Ref "AWS::Region"
                      - ":"
                      - !Ref "AWS::AccountId"
                      - ":layer:"
                      - "*"
        - PolicyName: CloudformationPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource:
                  - !Join
                    - ""
                    - - "arn:aws:cloudformation:"
                      - !Ref "AWS::Region"
                      - ":"
                      - !Ref "AWS::AccountId"
                      - ":stack/Apac"
                      - !Ref Country
                      - !Ref Environment
                      - !Ref ServiceName
                      - "/"
                      - "*"
                  - !Join
                    - ""
                    - - "arn:aws:cloudformation:"
                      - !Ref "AWS::Region"
                      - ":aws:transform/*"
        - PolicyName: IamPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:*
                Resource:
                  - !Join
                    - ""
                    - - "arn:aws:iam::"
                      - !Ref "AWS::AccountId"
                      - ":role/Apac"
                      - !Ref Country
                      - !Ref Environment
                      - !Ref ServiceName
                      - "*"
        - PolicyName: EC2Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:DescribeInstances"
                  - "ec2:DescribeImages"
                  - "ec2:DescribeKeyPairs"
                  - "ec2:DescribeVpcs"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeSecurityGroups"
                Resource: "*"
        - PolicyName: AWSKinesisPut
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action:
                  - "kinesis:PutRecord"
                  - "kinesis:PutRecords"
                  - "kinesis:DescribeStream"
                Resource: "*"
              - Effect: Allow
                Action: "cloudwatch:PutMetricData"
                Resource: "*"
  CICDBuildProject:
    Type: "AWS::CodeBuild::Project"
    DependsOn:
      - CiCdIamRole
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Description: !Sub
        - " Code Build Project for ${Service}."
        - Service: !Ref ServiceName
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: Country
            Type: PLAINTEXT
            Value: !Ref Country
          - Name: Environment
            Type: PLAINTEXT
            Value: !Ref Environment
          - Name: ServiceName
            Type: PLAINTEXT
            Value: !Ref ServiceName
          - Name: Stage
            Type: PLAINTEXT
            Value: !Ref Stage
          - Name: GitHubBranch
            Type: PLAINTEXT
            Value: !Ref GitHubBranch
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:3.0"
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      TimeoutInMinutes: 30
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      Name: !Join
        - ""
        - - !Ref Region
          - !Ref Country
          - !Ref Environment
          - !Ref ServiceName
      ServiceRole: !GetAtt
        - CiCdIamRole
        - Arn
      Source:
        Type: GITHUB
        Location: !Ref GitHubRepo
        BuildSpec: cicd/buildspec.yml
      SourceVersion: !Ref GitHubBranch
      Tags:
        - Key: Name
          Value: !Join
            - ""
            - - !Ref Region
              - !Ref Country
              - !Ref Environment
              - !Ref ServiceName
Outputs: {}
